apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: centos
spec:
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    env:
    - name: BITBUCKET_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ms-provisioner
          key: bitbucket_auth_password
    - name: JENKINS_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ms-provisioner
          key: jenkins_auth_password
    - name: SLACK_TOKEN
      valueFrom:
        secretKeyRef:
          name: ms-provisioner
          key: slack_token